FROM php:8.0-apache

RUN docker-php-ext-install pdo pdo_mysql

COPY . /var/www/html/
RUN chmod 644 /var/www/html/login.php \
 && chmod 644 /var/www/html/seed.php \
 && chmod 755 /var/www/html/migration.sh

EXPOSE 80
CMD ["/var/www/html/migration.sh"]